version: '3.8'

services:
  app:
    build: .
    container_name: rural-healthcare-app
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL=/app/database/healthcare.db
      - JWT_SECRET=${JWT_SECRET:-change_this_in_production}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:3000}
    volumes:
      - ./database:/app/database
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - healthcare-network

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: rural-healthcare-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - healthcare-network

networks:
  healthcare-network:
    driver: bridge

volumes:
  database:
  uploads:
  logs: